let express = require('express');
let router = express.Router();
let Schema = require('../database/schema');
const nodemailer = require('nodemailer');
require('dotenv/config');

router.post('/', function (req, res, next) {
	console.log("MAIL ROUTE");
	console.log(req.user);
	let transporter = nodemailer.createTransport({
		service: "Gmail",
		secure: false, // true for 465, false for other ports
		auth: {
			user: process.env.MAILUSER, // generated ethereal user
			pass: process.env.MAILPASSWORD           // generated ethereal password
		}
	});
	// setup email data with unicode symbols
	let mailOptions = {
		from: 'ADSurveillance', // sender address
		to: req.user.Email, // list of receivers
		subject: 'ADSurveillance Autogenerated Mail (do not reply)', // Subject line
		
		text: 'There might be a Car Accident of your family member ',
		html: '<b>There might be a Car Accident of your family member.<br> Nearest hospitals and police station have been informed. <br>Kindly reach there as soon as possible. </b>'
	};
	// send mail with defined transport object
	transporter.sendMail(mailOptions, (error, info) => {
		if (error) {
			return console.log(error);
		}
		console.log('Message sent: %s', info.messageId);
		// Preview only available when sending through an Ethereal account
		console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
	});
	res.send("MAIL SEND");
});

/* GET Admin Login page. */
// router.get('/', function(req, res, next) {
//   // res.render('index', { title: 'Express' });
//     res.redirect('/AdminLogin.html');
// });

module.exports = router;
